# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as a parent image
FROM node:16-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the project using rollup
RUN npm run build

# Stage to hold the final output
FROM node:16-alpine AS release

WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/dist /app/dist

# Since this is a library, we're not defining a CMD or ENTRYPOINT

# Instructions to use the library
# Instruct users to mount their own application and use the dist files
